/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

class AppTest {
    @Test fun testFetchLatestBulletinUrl() {
        val url = fetchLatestBulletinUrl()
        assertNotNull(url, "fetchLatestBulletinUrl should return a URL")
        assertTrue(url!!.startsWith("https://"), "URL should start with https://")
    }
}
